var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(a,c,b){a instanceof String&&(a=String(a));for(var e=a.length,d=0;d<e;d++){var f=a[d];if(c.call(b,f,d,a))return{i:d,v:f}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,c,b){a!=Array.prototype&&a!=Object.prototype&&(a[c]=b.value)};
$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(a,c,b,e){if(c){b=$jscomp.global;a=a.split(".");for(e=0;e<a.length-1;e++){var d=a[e];d in b||(b[d]={});b=b[d]}a=a[a.length-1];e=b[a];c=c(e);c!=e&&null!=c&&$jscomp.defineProperty(b,a,{configurable:!0,writable:!0,value:c})}};
$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,b){return $jscomp.findInternal(this,a,b).v}},"es6","es3");
(function(a){a(".main > .loading").fadeOut();var c=void 0,b=void 0,e="";(function(a){luciLocation="admin"==a[0]?[a[1],a[2]]:a;for(var b in luciLocation)e+=luciLocation[b],b!=luciLocation.length-1&&(e+="/")})(luciLocation);a(".main > .main-left > .nav > .slide > .menu").click(function(){var b=a(this).next(".slide-menu"),c=a(this);b.is(":visible")?b.stop(!0).slideUp("fast",function(){c.removeClass("active");b.removeClass("active")}):(c.addClass("active"),b.addClass("active"),b.stop(!0).slideDown("fast"));
return!1});a(".main > .main-left > .nav > .slide > .slide-menu > li > a").click(function(){void 0!=c&&c.removeClass("active");a(this).parent().addClass("active");a(".main > .loading").fadeIn("fast");return!0});a(".main > .main-left > .nav > .slide > .slide-menu > li").click(function(){void 0!=c&&c.removeClass("active");a(this).addClass("active");a(".main > .loading").fadeIn("fast");window.location=a(a(this).find("a")[0]).attr("href");return!1});(function(){var b=!1;if(!a("body").hasClass("logged-in"))return luciLocation=
["Main","Login"],!0;a(".main > .main-left > .nav > .slide > .menu").each(function(){var d=a(this);d.next().find("a").each(function(){var f=a(this);if(-1!=f.attr("href").indexOf(e))return d.click(),d.next(".slide-menu").stop(!0,!0),c=f.parent(),c.addClass("active"),b=!0})});return b})()&&(b="node-"+luciLocation[0]+"-"+luciLocation[1],b=b.replace(/[ \t\n\r\/]+/g,"_").toLowerCase(),a("body").addClass(b));a(".cbi-button-up").val("\ue20a");a(".cbi-button-down").val("\ue20b");a("#maincontent > .container").find("a").each(function(){var b=
a(this),c=b.attr("onclick");void 0!=c&&""!=c||b.click(function(){if(-1==b.attr("href").indexOf("#"))return a(".main > .loading").fadeIn("fast"),!0})});var d=!1;a(".showSide").click(function(){d?(a(".darkMask").stop(!0).fadeOut("fast"),a(".main-left").stop(!0).animate({width:"0"},"fast"),a(".main-right").css("overflow-y","auto"),d=!1):(a(".darkMask").stop(!0).fadeIn("fast"),a(".main-left").stop(!0).animate({width:"15rem"},"fast"),a(".main-right").css("overflow-y","hidden"),d=!0)});a(".darkMask").click(function(){d&&
(d=!1,a(".darkMask").stop(!0).fadeOut("fast"),a(".main-left").stop(!0).animate({width:"0"},"fast"),a(".main-right").css("overflow-y","auto"))});a(window).resize(function(){921<a(window).width()&&(a(".main-left").css("width",""),a(".darkMask").stop(!0),a(".darkMask").css("display","none"),d=!1)});a("legend").each(function(){var b=a(this);b.after("<span class='panel-title'>"+b.text()+"</span>")});a(".main-right").focus();a(".main-right").blur();a("input").attr("size","0");if(void 0!=b)switch(console.log(b),
b){case "node-status-system_log":case "node-status-kernel_log":a("#syslog").focus(function(){a("#syslog").blur();a(".main-right").focus();a(".main-right").blur()});break;case "node-status-firewall":b=a(".node-status-firewall > .main fieldset li > a");b.addClass("cbi-button cbi-button-reset a-to-btn");break;case "node-system-reboot":b=a(".node-system-reboot > .main > .main-right p > a"),b.addClass("cbi-button cbi-input-reset a-to-btn")}})(jQuery);
